export const QUERY_KEY = {
    // auth
    POST_LOGIN: 'POST_LOGIN',
    // transaction
    GET_TRANSACTION: 'GET_TRANSACTION',
    GET_TRANSACTION_HISTORY: 'GET_TRANSACTION_HISTORY',
    ADD_TRANSACTION_1: 'GET_TRANSACTION_1',
    POST_TRANSACTION: 'POST_TRANSACTION',
    PUT_TRANSACTION: 'PUT_TRANSACTION',
    DELETE_TRANSACTION: 'DELETE_TRANSACTION',
};
